# -*- coding: utf-8 -*-
"""01_eda_fab_process_yield.ipynb의 사본

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19rdYzFddK-nlzFAG4Jm2K83HL-IHmXz1
"""

import pandas as pd
import numpy as np

from google.colab import files

uploaded = files.upload()

print(uploaded.keys())

import pandas as pd
import numpy as np

file_name = "fab_process_yield.csv"
df = pd.read_csv(file_name)

print(df.shape)
df.head()

time_col = "Time"
target_col = "Pass/Fail"
feature_cols = df.columns[1:-1]

X = df[feature_cols]

print("=== 열 구조 ===")
print("전체 데이터 크기:", df.shape)
print("시간 열:", df.columns[0])
print("첫 센서:", feature_cols[0])
print("마지막 센서:", feature_cols[-1])
print("센서 수:", len(feature_cols))
print("타깃 열:", df.columns[-1])

print("\n=== 라벨 분포 ===")
print(df[target_col].value_counts(dropna=False))
print((df[target_col].value_counts(normalize=True) * 100).round(2))

print("\n=== 자료형 ===")
numeric_cols = X.select_dtypes(include=np.number).columns
non_numeric_cols = X.select_dtypes(exclude=np.number).columns

print("숫자형 센서 수:", len(numeric_cols))
print("비숫자형 센서 수:", len(non_numeric_cols))
print("비숫자형 센서 목록:", non_numeric_cols.tolist())

missing_count = X.isna().sum()
missing_rate = X.isna().mean()

zero_count = X.eq(0).sum()
zero_rate = X.eq(0).mean()

unique_count = X.nunique(dropna=True)
constant_cols = unique_count[unique_count <= 1].index.tolist()

print("=== 데이터 품질 ===")
print("전체 결측값 수:", int(missing_count.sum()))
print("전체 0 값 수:", int(zero_count.sum()))
print("결측이 있는 센서 수:", int((missing_count > 0).sum()))
print("결측률 20% 이상 센서 수:", int((missing_rate >= 0.20).sum()))
print("결측률 50% 이상 센서 수:", int((missing_rate >= 0.50).sum()))
print("상수 센서 수:", len(constant_cols))
print("완전 중복 행 수:", int(df.duplicated().sum()))

print("\n결측률 상위 10개 센서")
display(
    pd.DataFrame({
        "결측 개수": missing_count,
        "결측률(%)": missing_rate * 100
    }).sort_values("결측률(%)", ascending=False).head(10)
)

print("\n0 비율 상위 10개 센서")
display(
    pd.DataFrame({
        "0 개수": zero_count,
        "0 비율(%)": zero_rate * 100
    }).sort_values("0 비율(%)", ascending=False).head(10)
)

print("\n상수 센서 목록")
print(constant_cols)

df["Time"] = pd.to_datetime(df["Time"], errors="coerce")

print("시간 변환 실패:", df["Time"].isna().sum())
print("최초 시간:", df["Time"].min())
print("최종 시간:", df["Time"].max())
print("시간순 정렬 여부:", df["Time"].is_monotonic_increasing)
print("중복 시간 수:", df["Time"].duplicated().sum())

raw_df = pd.read_csv("fab_process_yield.csv")

print(raw_df["Time"].head(10).tolist())
print(raw_df["Time"].tail(10).tolist())

df["Time"] = pd.to_datetime(df["Time"], errors="coerce")
df["month"] = df["Time"].dt.to_period("M").astype(str)

print(df["month"].value_counts().sort_index())

# 센서와 타깃 분리
feature_cols = [str(i) for i in range(590)]

# 열 이름이 정수형으로 읽혔다면 이 코드가 자동 대응
if "0" not in df.columns:
    feature_cols = list(range(590))

X = df[feature_cols]
y = df["Pass/Fail"].map({
    -1: 0,  # Pass
     1: 1   # Fail
})

print("X 크기:", X.shape)
print("y 분포:")
print(y.value_counts())
print("타깃 변환 결측:", y.isna().sum())

# 상수 센서
constant_cols = X.columns[
    X.nunique(dropna=True) <= 1
].tolist()

# 결측률 50% 이상 센서
missing_rate = X.isna().mean()
high_missing_cols = missing_rate[
    missing_rate >= 0.50
].index.tolist()

# 중복 제거 대상 통합
drop_cols = list(set(constant_cols) | set(high_missing_cols))

X_clean = X.drop(columns=drop_cols)

print("원래 센서 수:", X.shape[1])
print("상수 센서 수:", len(constant_cols))
print("결측률 50% 이상 센서 수:", len(high_missing_cols))
print("실제 제거 센서 수:", len(drop_cols))
print("남은 센서 수:", X_clean.shape[1])
print("남은 결측값 수:", int(X_clean.isna().sum().sum()))

"""[1차 데이터 탐색 결과]

- 데이터 크기: 1,567행 × 592열
- 센서 수: 590개
- Pass: 1,463건
- Fail: 104건
- Fail 비율: 6.64%
- 전체 결측값: 41,951개
- 결측이 있는 센서: 538개
- 상수 센서: 116개
- 결측률 50% 이상 센서: 28개
- 제거 후 센서: 446개
- 제거 후 남은 결측값: 10,868개
- 완전 중복 행: 0개
- 분석 기간: 2008년 1월~12월
"""

# target 생성
y = df["Pass/Fail"].map({
    -1: 0,
     1: 1
})

print(y.value_counts())

print(X_clean.shape)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_clean,
    y,
    test_size=0.2,
    stratify=y,
    random_state=42
)

print(X_train.shape)
print(X_test.shape)

print(y_train.value_counts())
print(y_test.value_counts())

from sklearn.pipeline import Pipeline

from sklearn.impute import SimpleImputer

from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import LogisticRegression

pipe = Pipeline([

    ("imputer",
     SimpleImputer(strategy="median")),

    ("scaler",
     StandardScaler()),

    ("model",
     LogisticRegression(
         class_weight="balanced",
         max_iter=3000,
         random_state=42
     ))
])

pipe.fit(
    X_train,
    y_train
)

pred = pipe.predict(X_test)
prob = pipe.predict_proba(X_test)[:, 1]

from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    average_precision_score
)

print("=== Classification Report ===")
print(classification_report(y_test, pred, digits=4))

print("=== Confusion Matrix ===")
print(confusion_matrix(y_test, pred))

print("Accuracy:", round(accuracy_score(y_test, pred), 4))
print("Precision:", round(precision_score(y_test, pred), 4))
print("Recall:", round(recall_score(y_test, pred), 4))
print("F1:", round(f1_score(y_test, pred), 4))
print("PR-AUC:", round(average_precision_score(y_test, prob), 4))

import matplotlib.pyplot as plt

label_counts = y.value_counts().sort_index()

plt.figure(figsize=(5,4))
plt.bar(["Pass", "Fail"], label_counts.values)

plt.title("Pass / Fail Distribution")
plt.ylabel("Count")

for i, v in enumerate(label_counts.values):
    plt.text(i, v+10, str(v), ha="center")

plt.show()

"""day3"""

# Commented out IPython magic to ensure Python compatibility.
# 현재 변수 확인
# %whos

"""1. Random Forest Feature Importance

이 모델을 만든 객체가 현재 변수명으로 안 남아있어, 같은 조건으로 다시 생성해서 저장
"""

from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(
    n_estimators=200,
    random_state=42,
    n_jobs=-1
)

rf_model.fit(X_train, y_train)

importance = rf_model.feature_importances_

feature_importance = pd.DataFrame({
    "sensor": X_train.columns,
    "importance": importance
})

feature_importance = feature_importance.sort_values(
    "importance",
    ascending=False
)

feature_importance.head(20)

[x for x in dir() if 'rf' in x.lower() or 'forest' in x.lower()]

plt.figure(figsize=(10,6))

top20 = feature_importance.head(20)

plt.barh(
    top20["sensor"].astype(str),
    top20["importance"]
)

plt.gca().invert_yaxis()
plt.xlabel("Importance")
plt.ylabel("Sensor")
plt.title("Top 20 Important Sensors (Random Forest)")
plt.show()

top_features = feature_importance.head(20)

top_features

top_features.to_csv(
    "rf_top20_sensor_importance.csv",
    index=False
)

print(rf_model)
print(rf_balanced)

"""day4"""

!pip install shap -q

import shap

# Random Forest SHAP Explainer
explainer = shap.TreeExplainer(rf_model)

# 테스트 데이터 SHAP 값 계산
shap_values = explainer.shap_values(X_test)

type(shap_values), len(shap_values)

shap_values.shape

shap.summary_plot(
    shap_values[:, :, 1],
    X_test,
    max_display=20
)

shap_importance = pd.DataFrame({
    "sensor": X_test.columns,
    "mean_abs_shap": np.abs(shap_values[:, :, 1]).mean(axis=0)
})

shap_importance = shap_importance.sort_values(
    by="mean_abs_shap",
    ascending=False
)

shap_importance.head(20)

rf_top20 = feature_importance.head(20).copy()
shap_top20 = shap_importance.head(20).copy()

print("=== Random Forest Top20 ===")
display(rf_top20)

print("=== SHAP Top20 ===")
display(shap_top20)

import matplotlib.pyplot as plt

plt.figure(figsize=(10,8))

shap.summary_plot(
    shap_fail,
    X_test,
    max_display=20,
    show=False
)

plt.tight_layout()
plt.savefig(
    "SHAP_summary_top20.png",
    dpi=300,
    bbox_inches="tight"
)

plt.show()

top5_sensor = feature_importance.head(5)["sensor"].tolist()

top5_sensor

for sensor in top5_sensor:
    shap.dependence_plot(
        sensor,
        shap_fail,
        X_test
    )

feature_importance.head(20).to_csv(
    "RF_feature_importance_top20.csv",
    index=False
)

shap_importance.head(20).to_csv(
    "SHAP_importance_top20.csv",
    index=False
)

fail_data = X_test[y_test == 1]

fail_data[top5_sensor].describe()

pass_data = X_test[y_test == 0]

compare = pd.DataFrame({
    "Pass_mean": pass_data[top5_sensor].mean(),
    "Fail_mean": fail_data[top5_sensor].mean()
})

compare

shap_top5_sensor = shap_importance.head(5)["sensor"].tolist()

shap_top5_sensor

extra_shap_sensor = [
    x for x in shap_top5_sensor
    if x not in top5_sensor
]

extra_shap_sensor

print(top5_sensor)
print(shap_top5_sensor)

print(type(top5_sensor[0]))
print(type(shap_top5_sensor[0]))

for sensor in extra_shap_sensor:
    shap.dependence_plot(
        sensor,
        shap_fail,
        X_test
    )

pass_data = X_test[y_test == 0]
fail_data = X_test[y_test == 1]

final_sensor = ['64', '65', '574', '59', '103', '562']

compare = pd.DataFrame({
    "Pass_mean": pass_data[final_sensor].mean(),
    "Fail_mean": fail_data[final_sensor].mean(),
    "Difference": fail_data[final_sensor].mean() - pass_data[final_sensor].mean()
})

compare

compare.to_csv(
    "sensor_pass_fail_comparison.csv",
    encoding="utf-8-sig"
)